# Generated by Django 5.2.9 on 2025-12-31 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(help_text='مبلغ به ریال')),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'کارت اعتباری'), ('debit_card', 'کارت بانکی'), ('bank_transfer', 'انتقال بانکی'), ('online_wallet', 'کیف پول الکترونیکی')], default='online_wallet', max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('refunded', 'بازگرداندی')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
