# Generated by Django 6.0 on 2025-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_payment_date_payment_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'کارت اعتباری'), ('debit_card', 'کارت بانکی'), ('bank_transfer', 'انتقال بانکی'), ('online_wallet', 'کیف پول الکترونیکی')], default='bank_transfer', max_length=20, null=True),
        ),
    ]
