# Generated by Django 6.0 on 2025-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'کارت اعتباری'), ('debit_card', 'کارت بانکی'), ('bank_transfer', 'انتقال بانکی'), ('online_wallet', 'کیف پول الکترونیکی')], default='online_wallet', max_length=30, null=True),
        ),
    ]
