# Generated by Django 5.2.9 on 2025-12-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ایرلاین')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('iata_code', models.CharField(max_length=2, unique=True, verbose_name='کد IATA')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'ایرلاین',
                'verbose_name_plural': 'ایرلاین\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('iata_code', models.CharField(max_length=3, unique=True, verbose_name='کد IATA')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('is_popular', models.BooleanField(default=False, verbose_name='شهر محبوب')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
    ]
