# Generated by Django 6.0 on 2025-12-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('toures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_airline', to='common.airline'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_destination', to='common.city'),
        ),
    ]
