# Generated by Django 6.0 on 2025-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
