# Generated by Django 5.2.9 on 2025-12-31 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تور')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ (برای URL)')),
                ('tour_type', models.CharField(choices=[('internal', 'داخلی'), ('external', 'خارجی')], max_length=20, verbose_name='نوع تور')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت تور (روز)')),
                ('departure_date', models.DateField(verbose_name='تاریخ رفت')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ برگشت')),
                ('price_per_person', models.PositiveBigIntegerField(verbose_name='قیمت به ریال (هر نفر)')),
                ('available_seats', models.PositiveIntegerField(verbose_name='ظرفیت موجود')),
                ('description', models.TextField(verbose_name='توضیحات تور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='تصویر اصلی تور')),
                ('featured', models.BooleanField(default=False, verbose_name='تور ویژه (نمایش در صفحه اصلی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_airline', to='common.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_destination', to='common.city')),
            ],
            options={
                'verbose_name': 'تور',
                'verbose_name_plural': 'تورها',
                'ordering': ['-departure_date'],
            },
        ),
    ]
