# Generated by Django 6.0 on 2025-12-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_arrivals', to='common.city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_departures', to='common.city'),
        ),
    ]
