# Generated by Django 6.0 on 2025-12-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_airline_alter_flight_destination_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price_per_seat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
