# Generated by Django 6.0 on 2025-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_price_per_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
