# Generated by Django 6.0 on 2025-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.PositiveBigIntegerField(help_text='مبلغ کل به ریال'),
        ),
    ]
